### ISSUE TITLE
Error parsing my address

### ISSUE THREAD

**Issue by schristmann** [datamade/usaddress#87]
Just gave your service a whirl by typing in an address that's pretty close to my own, but got an "Error parsing that address."

Here's the address I used

1234 Washington St. Unit 214, Denver, CO 80212

**Comment by derekeder** [comment]
@schristmann was this via the website? http://parserator.datamade.us/usaddress

We just pushed up some changes to that page that may require a hard refresh if you've visited before.

**Comment by schristmann** [comment]
Yeah this was on the website which was just linked to hacker news. Still getting the error

**Comment by fgregg** [comment]
This is the HN link https://news.ycombinator.com/item?id=9381354

I can't reproduce this.

**Comment by derekeder** [comment]
@schristmann trying to reproduce this too, but unable to. You guys caught us just as we were deploying a major release to a new server, so lots of funny stuff could be happening.

Could you try again now that the DNS has had more time to propagate?

**Comment by schristmann** [comment]
@derekeder Sorry still no luck, here's my request response capture

Request
```
GET /api/usaddress/?api_key=ac5e0a11-8406-4b94-a57f-b1a6661b0886&address=123%20Main%20St.%20Suite%20100%20Chicago%2C%20IL HTTP/1.1
Host: parserator.datamade.us
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
X-Requested-With: XMLHttpRequest
Referer: http://parserator.datamade.us/usaddress
Cookie: session=eyJfZnJlc2giOmZhbHNlLCJfaWQiOiI0OGIzMTVjNWE1NGI2MWFiODFmYjhhZDIyNDdmYjQ3ZSJ9.CBCaZw.19jVwT293VN8fSZq95ZDnnVIxoA; __utma=208592147.804575336.1429134877.1429134877.1429145549.2; __utmc=208592147; __utmz=208592147.1429134877.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmb=208592147.3.10.1429145549; __utmt=1
X-Forwarded-For: 12.13.14.15
Connection: keep-alive
```
Response
```
HTTP/1.1 500 INTERNAL SERVER ERROR
Server: nginx/1.1.19
Date: Thu, 16 Apr 2015 00:58:26 GMT
Content-Type: text/html
Content-Length: 291
Connection: keep-alive
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by cathydeng** [comment]
did you try a hard refresh? I can't reproduce this either
![screen shot 2015-04-15 at 7 58 12 pm](https://cloud.githubusercontent.com/assets/1406537/7172250/ecf9bf68-e3a9-11e4-92f8-99736b0b66bd.png)

**Comment by schristmann** [comment]
It looks like your server doesn't like the X-Forwarded-For: field being added by one of my extensions, after a quick disable it works now.

**Comment by derekeder** [comment]
@schristmann thanks - good to know! We'll look in to handling that header field.
